export interface Vale {
    id: number,
    idSAP: number,
    keySAPid: number,
    type: number,
    operador_Code: String,
    operador_Name: string,
    unidad_Code: String,
    unidad_Name: String,
    km_Inicial: number,
    km_Final: number,
    lbomba_Inicial: number,
    lbomba_Final: number,
    kmRecorridos: number,
    litrosSolicitados: number,
    litrosCargados: number,
    rendimiento_Optimo: number,
    rendimiento_Real: number,
    diferencia: number,
    timestamp: String,
    usuario: String,
    proveedor: String,
    proveedorName:String,
    empresa: String,
    sucursal: String,
    status:String,
    comentarios:String,
    tanqueLLeno: String,
    filePath: String
}